
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  6 2025 19:52:02 CEST (May  6 2025 17:52:02 UTC)

// Verification Directory fv/mips 

module alucontrol(aluop, funct, alucont);
  input [1:0] aluop;
  input [5:0] funct;
  output [2:0] alucont;
  wire [1:0] aluop;
  wire [5:0] funct;
  wire [2:0] alucont;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12;
  OAI21_X1 g485__2398(.A (aluop[1]), .B1 (funct[2]), .B2 (n_12), .ZN
       (alucont[1]));
  NAND2_X1 g486__5107(.A1 (n_6), .A2 (n_10), .ZN (alucont[2]));
  AND2_X1 g487__6260(.A1 (n_8), .A2 (n_7), .ZN (n_12));
  NOR2_X1 g488__4319(.A1 (n_1), .A2 (n_9), .ZN (alucont[0]));
  AOI22_X1 g489__8428(.A1 (aluop[1]), .A2 (n_5), .B1 (aluop[0]), .B2
       (n_1), .ZN (n_10));
  AOI21_X1 g490__5526(.A (n_7), .B1 (funct[2]), .B2 (funct[1]), .ZN
       (n_9));
  NAND3_X1 g491__6783(.A1 (funct[1]), .A2 (funct[5]), .A3 (n_3), .ZN
       (n_8));
  NAND2_X1 g492__3680(.A1 (n_4), .A2 (n_3), .ZN (n_7));
  OAI21_X1 g493__1617(.A (aluop[1]), .B1 (funct[4]), .B2 (funct[1]),
       .ZN (n_6));
  OAI21_X1 g494__2802(.A (n_4), .B1 (n_2), .B2 (funct[2]), .ZN (n_5));
  NOR2_X1 g495__1705(.A1 (n_0), .A2 (funct[3]), .ZN (n_4));
  NOR2_X1 g496__5122(.A1 (funct[4]), .A2 (funct[0]), .ZN (n_3));
  INV_X1 g497(.A (funct[0]), .ZN (n_2));
  INV_X1 g498(.A (aluop[1]), .ZN (n_1));
  INV_X1 g499(.A (funct[5]), .ZN (n_0));
endmodule

module controller(clk, reset, op, zero, memread, memwrite, alusrca,
     memtoreg, iord, pcen, regwrite, regdst, pcsource, alusrcb, aluop,
     irwrite);
  input clk, reset, zero;
  input [5:0] op;
  output memread, memwrite, alusrca, memtoreg, iord, pcen, regwrite,
       regdst;
  output [1:0] pcsource, alusrcb, aluop;
  output [3:0] irwrite;
  wire clk, reset, zero;
  wire [5:0] op;
  wire memread, memwrite, alusrca, memtoreg, iord, pcen, regwrite,
       regdst;
  wire [1:0] pcsource, alusrcb, aluop;
  wire [3:0] irwrite;
  wire [3:0] state;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_40, n_44, n_45;
  wire n_46, n_50, n_51, n_59, n_60, n_61, n_62, n_65;
  wire n_66, n_67, n_70, n_71, n_72, n_73, n_98, n_99;
  wire n_103, n_106, n_119, n_122, n_134, n_137, n_144, n_145;
  wire n_147, n_148, n_196, n_199, n_210, n_214, n_263, n_264;
  wire n_267, n_269, n_271, n_273;
  INV_X1 g1265(.A (zero), .ZN (n_65));
  INV_X1 g1267(.A (n_67), .ZN (aluop[1]));
  INV_X1 g1266(.A (n_73), .ZN (pcsource[0]));
  OAI21_X1 g1269__8246(.A (n_72), .B1 (n_65), .B2 (n_73), .ZN (pcen));
  OAI221_X1 g1360__7098(.A (n_62), .B1 (n_98), .B2 (n_44), .C1 (n_103),
       .C2 (n_119), .ZN (n_72));
  OAI22_X1 g1361__6131(.A1 (n_46), .A2 (n_59), .B1 (n_99), .B2 (n_44),
       .ZN (alusrcb[0]));
  NAND3_X1 g1362__1881(.A1 (n_73), .A2 (n_67), .A3 (n_61), .ZN
       (alusrca));
  OR2_X1 g1364__7482(.A1 (regdst), .A2 (memtoreg), .ZN (regwrite));
  OR2_X4 g1365__4733(.A1 (memwrite), .A2 (n_60), .ZN (iord));
  OAI21_X1 g1366__6161(.A (n_61), .B1 (n_71), .B2 (n_44), .ZN
       (alusrcb[1]));
  AOI211_X1 g1367__9315(.A (n_40), .B (n_51), .C1 (n_46), .C2 (n_98),
       .ZN (n_62));
  NOR2_X1 g1369__2883(.A1 (n_267), .A2 (n_145), .ZN (pcsource[1]));
  NOR2_X1 g1370__2346(.A1 (n_50), .A2 (n_147), .ZN (n_60));
  NOR2_X1 g1371__1666(.A1 (n_210), .A2 (n_145), .ZN (regdst));
  NAND2_X1 g1373__6417(.A1 (n_264), .A2 (n_40), .ZN (n_61));
  NOR2_X1 g1374__5477(.A1 (n_44), .A2 (n_119), .ZN (irwrite[0]));
  NOR2_X1 g1375__2398(.A1 (n_210), .A2 (n_44), .ZN (irwrite[2]));
  NOR2_X1 g1376__5107(.A1 (n_269), .A2 (n_214), .ZN (n_59));
  NAND2_X1 g1377__6260(.A1 (n_214), .A2 (n_51), .ZN (n_67));
  NAND2_X1 g1379__8428(.A1 (n_269), .A2 (n_51), .ZN (n_73));
  NAND2_X1 g1385__3680(.A1 (n_98), .A2 (n_148), .ZN (n_70));
  NAND2_X1 g1386__1617(.A1 (n_99), .A2 (n_37), .ZN (n_71));
  NOR2_X1 g1392__5122(.A1 (n_45), .A2 (n_106), .ZN (n_51));
  NAND2_X1 g1393__8246(.A1 (state[2]), .A2 (state[1]), .ZN (n_50));
  INV_X1 g1398(.A (n_46), .ZN (n_45));
  BUF_X1 fopt5(.A (n_147), .Z (n_44));
  INV_X1 fopt1404(.A (n_40), .ZN (n_66));
  INV_X1 fopt1405(.A (n_50), .ZN (n_40));
  DFF_X1 \state_reg[1] (.CK (clk), .D (n_34), .Q (state[1]), .QN
       (n_37));
  DFF_X1 \state_reg[2] (.CK (clk), .D (n_32), .Q (state[2]), .QN
       (n_36));
  DFF_X1 \state_reg[3] (.CK (clk), .D (n_196), .Q (state[3]), .QN
       (n_35));
  INV_X1 g1410(.A (n_33), .ZN (n_34));
  AOI221_X1 g1411__6131(.A (n_10), .B1 (n_148), .B2 (n_29), .C1 (n_7),
       .C2 (n_23), .ZN (n_33));
  OAI222_X1 g1412__1881(.A1 (n_36), .A2 (n_30), .B1 (n_267), .B2
       (n_28), .C1 (n_210), .C2 (n_6), .ZN (n_32));
  DFF_X1 \state_reg[0] (.CK (clk), .D (n_25), .Q (state[0]), .QN
       (n_38));
  INV_X1 g1415(.A (n_29), .ZN (n_30));
  AOI221_X1 g1416__7482(.A (n_22), .B1 (n_122), .B2 (n_20), .C1
       (op[2]), .C2 (n_19), .ZN (n_28));
  NOR3_X1 g1417__4733(.A1 (op[3]), .A2 (n_103), .A3 (n_21), .ZN (n_29));
  NAND2_X1 g1418__6161(.A1 (op[3]), .A2 (n_22), .ZN (n_27));
  INV_X1 g1419(.A (n_24), .ZN (n_26));
  OAI21_X1 g1420__9315(.A (n_7), .B1 (n_267), .B2 (n_17), .ZN (n_25));
  OAI21_X1 g1421__9945(.A (n_66), .B1 (n_36), .B2 (n_18), .ZN (n_24));
  NAND2_X1 g1422__2883(.A1 (n_119), .A2 (n_16), .ZN (n_23));
  INV_X1 g1423(.A (n_21), .ZN (n_22));
  OAI21_X1 g1424__2346(.A (n_103), .B1 (n_1), .B2 (n_13), .ZN (n_20));
  NAND3_X1 g1425__1666(.A1 (n_2), .A2 (op[5]), .A3 (n_15), .ZN (n_21));
  AND2_X1 g1426__7410(.A1 (n_3), .A2 (n_15), .ZN (n_19));
  AOI21_X1 g1427__6417(.A (n_14), .B1 (n_3), .B2 (n_12), .ZN (n_18));
  AOI211_X1 g1428__5477(.A (n_9), .B (n_11), .C1 (op[5]), .C2 (op[2]),
       .ZN (n_17));
  NAND4_X1 g1429__2398(.A1 (n_37), .A2 (n_2), .A3 (n_8), .A4 (n_12),
       .ZN (n_16));
  AND2_X1 g1430__5107(.A1 (n_122), .A2 (n_12), .ZN (n_15));
  INV_X1 g1431(.A (n_13), .ZN (n_14));
  NAND3_X1 g1432__6260(.A1 (n_2), .A2 (n_3), .A3 (n_5), .ZN (n_13));
  INV_X1 g1433(.A (n_11), .ZN (n_12));
  NAND2_X1 g1434__4319(.A1 (n_1), .A2 (n_5), .ZN (n_11));
  NOR3_X1 g1435__8428(.A1 (n_210), .A2 (reset), .A3 (n_103), .ZN
       (n_10));
  INV_X1 g1436(.A (n_8), .ZN (n_9));
  INV_X1 g1437(.A (n_7), .ZN (n_6));
  NAND2_X1 g1438__5526(.A1 (op[3]), .A2 (n_0), .ZN (n_8));
  NOR2_X1 g1439__6783(.A1 (reset), .A2 (n_44), .ZN (n_7));
  NOR2_X1 g1440__3680(.A1 (op[4]), .A2 (op[0]), .ZN (n_5));
  NOR2_X1 g1442__2802(.A1 (op[5]), .A2 (op[3]), .ZN (n_3));
  INV_X1 g1445(.A (op[2]), .ZN (n_2));
  INV_X1 g1446(.A (op[1]), .ZN (n_1));
  INV_X1 g1449(.A (op[5]), .ZN (n_0));
  INV_X1 fopt(.A (n_99), .ZN (n_98));
  BUF_X1 fopt1451(.A (state[2]), .Z (n_99));
  CLKBUF_X1 fopt1454(.A (n_106), .Z (n_103));
  CLKBUF_X1 fopt1455(.A (state[0]), .Z (n_106));
  INV_X1 g1464(.A (n_134), .ZN (n_119));
  NOR2_X1 g1441__1465(.A1 (n_46), .A2 (reset), .ZN (n_122));
  AND2_X1 g1378__1481(.A1 (n_134), .A2 (n_51), .ZN (memtoreg));
  CLKBUF_X1 g1(.A (n_137), .Z (n_134));
  NOR2_X1 g1394__1482(.A1 (state[2]), .A2 (state[1]), .ZN (n_137));
  AND2_X1 g1380__1485(.A1 (n_199), .A2 (n_137), .ZN (memwrite));
  INV_X1 g1487(.A (n_144), .ZN (n_145));
  CLKBUF_X1 g1488(.A (n_199), .Z (n_144));
  NAND2_X1 g1387__1490(.A1 (state[0]), .A2 (n_35), .ZN (n_147));
  INV_X1 fopt1491(.A (n_37), .ZN (n_148));
  NOR2_X1 g1372__1495(.A1 (n_267), .A2 (n_263), .ZN (irwrite[3]));
  OAI222_X1 g1363__1498(.A1 (n_271), .A2 (n_44), .B1 (n_71), .B2
       (n_273), .C1 (n_70), .C2 (n_46), .ZN (memread));
  NOR2_X1 g1368__1499(.A1 (n_210), .A2 (n_263), .ZN (irwrite[1]));
  OAI222_X1 g1413__1500(.A1 (n_66), .A2 (n_27), .B1 (n_6), .B2 (n_26),
       .C1 (reset), .C2 (n_67), .ZN (n_196));
  BUF_X1 fopt1502(.A (state[3]), .Z (n_46));
  AND2_X1 g1384__1503(.A1 (state[0]), .A2 (state[3]), .ZN (n_199));
  INV_X1 fopt1517(.A (n_214), .ZN (n_210));
  INV_X1 fopt4(.A (n_70), .ZN (n_214));
  INV_X1 fopt1562(.A (n_264), .ZN (n_263));
  INV_X1 fopt1(.A (n_273), .ZN (n_264));
  INV_X1 fopt1565(.A (n_269), .ZN (n_267));
  INV_X1 fopt1566(.A (n_71), .ZN (n_269));
  INV_X1 fopt1567(.A (n_71), .ZN (n_271));
  OR2_X1 g2(.A1 (n_46), .A2 (n_106), .ZN (n_273));
endmodule

module mux2_WIDTH8(d0, d1, s, y);
  input [7:0] d0, d1;
  input s;
  output [7:0] y;
  wire [7:0] d0, d1;
  wire s;
  wire [7:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  OAI21_X1 g188__1705(.A (n_14), .B1 (n_6), .B2 (s), .ZN (y[1]));
  OAI21_X1 g189__5122(.A (n_15), .B1 (n_2), .B2 (s), .ZN (y[4]));
  OAI21_X1 g190__8246(.A (n_9), .B1 (n_1), .B2 (s), .ZN (y[7]));
  OAI21_X1 g191__7098(.A (n_12), .B1 (n_7), .B2 (s), .ZN (y[0]));
  OAI21_X1 g192__6131(.A (n_11), .B1 (n_0), .B2 (s), .ZN (y[5]));
  OAI21_X1 g193__1881(.A (n_13), .B1 (n_5), .B2 (s), .ZN (y[6]));
  OAI21_X1 g194__5115(.A (n_10), .B1 (n_4), .B2 (s), .ZN (y[3]));
  OAI21_X1 g195__7482(.A (n_8), .B1 (n_3), .B2 (s), .ZN (y[2]));
  NAND2_X1 g196__4733(.A1 (d1[4]), .A2 (s), .ZN (n_15));
  NAND2_X1 g197__6161(.A1 (d1[1]), .A2 (s), .ZN (n_14));
  NAND2_X1 g198__9315(.A1 (d1[6]), .A2 (s), .ZN (n_13));
  NAND2_X1 g199__9945(.A1 (d1[0]), .A2 (s), .ZN (n_12));
  NAND2_X1 g200__2883(.A1 (d1[5]), .A2 (s), .ZN (n_11));
  NAND2_X1 g201__2346(.A1 (d1[3]), .A2 (s), .ZN (n_10));
  NAND2_X1 g202__1666(.A1 (d1[7]), .A2 (s), .ZN (n_9));
  NAND2_X1 g203__7410(.A1 (d1[2]), .A2 (s), .ZN (n_8));
  INV_X1 g204(.A (d0[0]), .ZN (n_7));
  INV_X1 g205(.A (d0[1]), .ZN (n_6));
  INV_X1 g206(.A (d0[6]), .ZN (n_5));
  INV_X1 g207(.A (d0[3]), .ZN (n_4));
  INV_X1 g208(.A (d0[2]), .ZN (n_3));
  INV_X1 g209(.A (d0[4]), .ZN (n_2));
  INV_X1 g210(.A (d0[7]), .ZN (n_1));
  INV_X1 g211(.A (d0[5]), .ZN (n_0));
endmodule

module flop_WIDTH8_53(clk, d, q);
  input clk;
  input [7:0] d;
  output [7:0] q;
  wire clk;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  DFF_X1 \q_reg[2] (.CK (clk), .D (d[2]), .Q (q[2]), .QN (UNCONNECTED));
  DFF_X1 \q_reg[1] (.CK (clk), .D (d[1]), .Q (q[1]), .QN
       (UNCONNECTED0));
  DFF_X1 \q_reg[0] (.CK (clk), .D (d[0]), .Q (q[0]), .QN
       (UNCONNECTED1));
  DFF_X1 \q_reg[3] (.CK (clk), .D (d[3]), .Q (q[3]), .QN
       (UNCONNECTED2));
  DFF_X1 \q_reg[6] (.CK (clk), .D (d[6]), .Q (q[6]), .QN
       (UNCONNECTED3));
  DFF_X1 \q_reg[5] (.CK (clk), .D (d[5]), .Q (q[5]), .QN
       (UNCONNECTED4));
  DFF_X1 \q_reg[4] (.CK (clk), .D (d[4]), .Q (q[4]), .QN
       (UNCONNECTED5));
  DFF_X1 \q_reg[7] (.CK (clk), .D (d[7]), .Q (q[7]), .QN
       (UNCONNECTED6));
endmodule

module flopen_WIDTH8(clk, en, d, q);
  input clk, en;
  input [7:0] d;
  output [7:0] q;
  wire clk, en;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  SDFF_X1 \q_reg[4] (.CK (clk), .D (q[4]), .SE (en), .SI (d[4]), .Q
       (q[4]), .QN (UNCONNECTED7));
  SDFF_X1 \q_reg[3] (.CK (clk), .D (q[3]), .SE (en), .SI (d[3]), .Q
       (q[3]), .QN (UNCONNECTED8));
  SDFF_X1 \q_reg[0] (.CK (clk), .D (q[0]), .SE (en), .SI (d[0]), .Q
       (q[0]), .QN (UNCONNECTED9));
  SDFF_X1 \q_reg[5] (.CK (clk), .D (q[5]), .SE (en), .SI (d[5]), .Q
       (q[5]), .QN (UNCONNECTED10));
  SDFF_X1 \q_reg[7] (.CK (clk), .D (q[7]), .SE (en), .SI (d[7]), .Q
       (q[7]), .QN (UNCONNECTED11));
  SDFF_X1 \q_reg[1] (.CK (clk), .D (q[1]), .SE (en), .SI (d[1]), .Q
       (q[1]), .QN (UNCONNECTED12));
  SDFF_X1 \q_reg[6] (.CK (clk), .D (q[6]), .SE (en), .SI (d[6]), .Q
       (q[6]), .QN (UNCONNECTED13));
  SDFF_X1 \q_reg[2] (.CK (clk), .D (q[2]), .SE (en), .SI (d[2]), .Q
       (q[2]), .QN (UNCONNECTED14));
endmodule

module flopen_WIDTH8_56(clk, en, d, q);
  input clk, en;
  input [7:0] d;
  output [7:0] q;
  wire clk, en;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  SDFF_X1 \q_reg[3] (.CK (clk), .D (q[3]), .SE (en), .SI (d[3]), .Q
       (q[3]), .QN (UNCONNECTED15));
  SDFF_X1 \q_reg[4] (.CK (clk), .D (q[4]), .SE (en), .SI (d[4]), .Q
       (q[4]), .QN (UNCONNECTED16));
  SDFF_X1 \q_reg[5] (.CK (clk), .D (q[5]), .SE (en), .SI (d[5]), .Q
       (q[5]), .QN (UNCONNECTED17));
endmodule

module flopen_WIDTH8_55(clk, en, d, q);
  input clk, en;
  input [7:0] d;
  output [7:0] q;
  wire clk, en;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23;
  SDFF_X1 \q_reg[0] (.CK (clk), .D (q[0]), .SE (en), .SI (d[0]), .Q
       (q[0]), .QN (UNCONNECTED18));
  SDFF_X1 \q_reg[1] (.CK (clk), .D (q[1]), .SE (en), .SI (d[1]), .Q
       (q[1]), .QN (UNCONNECTED19));
  SDFF_X1 \q_reg[6] (.CK (clk), .D (q[6]), .SE (en), .SI (d[6]), .Q
       (q[6]), .QN (UNCONNECTED20));
  SDFF_X1 \q_reg[7] (.CK (clk), .D (q[7]), .SE (en), .SI (d[7]), .Q
       (q[7]), .QN (UNCONNECTED21));
  SDFF_X1 \q_reg[2] (.CK (clk), .D (q[2]), .SE (en), .SI (d[2]), .Q
       (q[2]), .QN (UNCONNECTED22));
  SDFF_X1 \q_reg[5] (.CK (clk), .D (q[5]), .SE (en), .SI (d[5]), .Q
       (q[5]), .QN (UNCONNECTED23));
endmodule

module flopen_WIDTH8_54(clk, en, d, q);
  input clk, en;
  input [7:0] d;
  output [7:0] q;
  wire clk, en;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, UNCONNECTED27,
       UNCONNECTED28, UNCONNECTED29;
  SDFF_X1 \q_reg[2] (.CK (clk), .D (q[2]), .SE (en), .SI (d[2]), .Q
       (q[2]), .QN (UNCONNECTED24));
  SDFF_X1 \q_reg[3] (.CK (clk), .D (q[3]), .SE (en), .SI (d[3]), .Q
       (q[3]), .QN (UNCONNECTED25));
  SDFF_X1 \q_reg[6] (.CK (clk), .D (q[6]), .SE (en), .SI (d[6]), .Q
       (q[6]), .QN (UNCONNECTED26));
  SDFF_X1 \q_reg[7] (.CK (clk), .D (q[7]), .SE (en), .SI (d[7]), .Q
       (q[7]), .QN (UNCONNECTED27));
  SDFF_X1 \q_reg[4] (.CK (clk), .D (q[4]), .SE (en), .SI (d[4]), .Q
       (q[4]), .QN (UNCONNECTED28));
  SDFF_X1 \q_reg[5] (.CK (clk), .D (q[5]), .SE (en), .SI (d[5]), .Q
       (q[5]), .QN (UNCONNECTED29));
endmodule

module flop_WIDTH8(clk, d, q);
  input clk;
  input [7:0] d;
  output [7:0] q;
  wire clk;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33,
       UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37;
  DFF_X1 \q_reg[2] (.CK (clk), .D (d[2]), .Q (q[2]), .QN
       (UNCONNECTED30));
  DFF_X1 \q_reg[1] (.CK (clk), .D (d[1]), .Q (q[1]), .QN
       (UNCONNECTED31));
  DFF_X1 \q_reg[0] (.CK (clk), .D (d[0]), .Q (q[0]), .QN
       (UNCONNECTED32));
  DFF_X1 \q_reg[3] (.CK (clk), .D (d[3]), .Q (q[3]), .QN
       (UNCONNECTED33));
  DFF_X1 \q_reg[6] (.CK (clk), .D (d[6]), .Q (q[6]), .QN
       (UNCONNECTED34));
  DFF_X1 \q_reg[5] (.CK (clk), .D (d[5]), .Q (q[5]), .QN
       (UNCONNECTED35));
  DFF_X1 \q_reg[4] (.CK (clk), .D (d[4]), .Q (q[4]), .QN
       (UNCONNECTED36));
  DFF_X1 \q_reg[7] (.CK (clk), .D (d[7]), .Q (q[7]), .QN
       (UNCONNECTED37));
endmodule

module flopenr_WIDTH8(clk, reset, en, d, q);
  input clk, reset, en;
  input [7:0] d;
  output [7:0] q;
  wire clk, reset, en;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED38, UNCONNECTED39, UNCONNECTED40, UNCONNECTED41,
       UNCONNECTED42, UNCONNECTED43, UNCONNECTED44, UNCONNECTED45;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18;
  DFF_X1 \q_reg[3] (.CK (clk), .D (n_16), .Q (q[3]), .QN
       (UNCONNECTED38));
  DFF_X1 \q_reg[2] (.CK (clk), .D (n_7), .Q (q[2]), .QN
       (UNCONNECTED39));
  DFF_X1 \q_reg[0] (.CK (clk), .D (n_10), .Q (q[0]), .QN
       (UNCONNECTED40));
  DFF_X1 \q_reg[4] (.CK (clk), .D (n_17), .Q (q[4]), .QN
       (UNCONNECTED41));
  DFF_X1 \q_reg[6] (.CK (clk), .D (n_15), .Q (q[6]), .QN
       (UNCONNECTED42));
  DFF_X1 \q_reg[1] (.CK (clk), .D (n_8), .Q (q[1]), .QN
       (UNCONNECTED43));
  DFF_X1 \q_reg[5] (.CK (clk), .D (n_18), .Q (q[5]), .QN
       (UNCONNECTED44));
  DFF_X1 \q_reg[7] (.CK (clk), .D (n_9), .Q (q[7]), .QN
       (UNCONNECTED45));
  INV_X1 g265(.A (n_14), .ZN (n_18));
  INV_X1 g266(.A (n_13), .ZN (n_17));
  INV_X1 g267(.A (n_12), .ZN (n_16));
  INV_X1 g268(.A (n_11), .ZN (n_15));
  AOI22_X1 g269__6417(.A1 (q[5]), .A2 (n_1), .B1 (d[5]), .B2 (n_2), .ZN
       (n_14));
  AOI22_X1 g270__5477(.A1 (q[4]), .A2 (n_1), .B1 (d[4]), .B2 (n_2), .ZN
       (n_13));
  AOI22_X1 g271__2398(.A1 (q[3]), .A2 (n_1), .B1 (d[3]), .B2 (n_2), .ZN
       (n_12));
  AOI22_X1 g272__5107(.A1 (q[6]), .A2 (n_1), .B1 (d[6]), .B2 (n_2), .ZN
       (n_11));
  INV_X1 g273(.A (n_6), .ZN (n_10));
  INV_X1 g274(.A (n_5), .ZN (n_9));
  INV_X1 g275(.A (n_4), .ZN (n_8));
  INV_X1 g276(.A (n_3), .ZN (n_7));
  AOI22_X1 g277__6260(.A1 (q[0]), .A2 (n_1), .B1 (d[0]), .B2 (n_2), .ZN
       (n_6));
  AOI22_X1 g278__4319(.A1 (q[7]), .A2 (n_1), .B1 (d[7]), .B2 (n_2), .ZN
       (n_5));
  AOI22_X1 g279__8428(.A1 (q[1]), .A2 (n_1), .B1 (d[1]), .B2 (n_2), .ZN
       (n_4));
  AOI22_X1 g280__5526(.A1 (q[2]), .A2 (n_1), .B1 (d[2]), .B2 (n_2), .ZN
       (n_3));
  NOR2_X1 g281__6783(.A1 (n_0), .A2 (reset), .ZN (n_2));
  NOR2_X1 g282__3680(.A1 (reset), .A2 (en), .ZN (n_1));
  INV_X1 g283(.A (en), .ZN (n_0));
endmodule

module mux2_WIDTH3(d0, d1, s, y);
  input [2:0] d0, d1;
  input s;
  output [2:0] y;
  wire [2:0] d0, d1;
  wire s;
  wire [2:0] y;
  MUX2_X1 g56__1617(.A (d0[2]), .B (d1[2]), .S (s), .Z (y[2]));
  MUX2_X1 g57__2802(.A (d0[1]), .B (d1[1]), .S (s), .Z (y[1]));
  MUX2_X1 g58__1705(.A (d0[0]), .B (d1[0]), .S (s), .Z (y[0]));
endmodule

module flop_WIDTH8_51(clk, d, q);
  input clk;
  input [7:0] d;
  output [7:0] q;
  wire clk;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, UNCONNECTED49,
       UNCONNECTED50, UNCONNECTED51, UNCONNECTED52, UNCONNECTED53;
  DFF_X1 \q_reg[2] (.CK (clk), .D (d[2]), .Q (q[2]), .QN
       (UNCONNECTED46));
  DFF_X1 \q_reg[1] (.CK (clk), .D (d[1]), .Q (q[1]), .QN
       (UNCONNECTED47));
  DFF_X1 \q_reg[0] (.CK (clk), .D (d[0]), .Q (q[0]), .QN
       (UNCONNECTED48));
  DFF_X1 \q_reg[3] (.CK (clk), .D (d[3]), .Q (q[3]), .QN
       (UNCONNECTED49));
  DFF_X1 \q_reg[6] (.CK (clk), .D (d[6]), .Q (q[6]), .QN
       (UNCONNECTED50));
  DFF_X1 \q_reg[5] (.CK (clk), .D (d[5]), .Q (q[5]), .QN
       (UNCONNECTED51));
  DFF_X1 \q_reg[4] (.CK (clk), .D (d[4]), .Q (q[4]), .QN
       (UNCONNECTED52));
  DFF_X1 \q_reg[7] (.CK (clk), .D (d[7]), .Q (q[7]), .QN
       (UNCONNECTED53));
endmodule

module regfile_WIDTH8_REGBITS3(clk, regwrite, ra1, ra2, wa, wd, rd1,
     rd2);
  input clk, regwrite;
  input [2:0] ra1, ra2, wa;
  input [7:0] wd;
  output [7:0] rd1, rd2;
  wire clk, regwrite;
  wire [2:0] ra1, ra2, wa;
  wire [7:0] wd;
  wire [7:0] rd1, rd2;
  wire [7:0] \RAM[6] ;
  wire [7:0] \RAM[5] ;
  wire [7:0] \RAM[1] ;
  wire [7:0] \RAM[2] ;
  wire [7:0] \RAM[3] ;
  wire [7:0] \RAM[4] ;
  wire [7:0] \RAM[7] ;
  wire UNCONNECTED54, UNCONNECTED55, UNCONNECTED56, UNCONNECTED57,
       UNCONNECTED58, UNCONNECTED59, UNCONNECTED60, UNCONNECTED61;
  wire UNCONNECTED62, UNCONNECTED63, UNCONNECTED64, UNCONNECTED65,
       UNCONNECTED66, UNCONNECTED67, UNCONNECTED68, UNCONNECTED69;
  wire UNCONNECTED70, UNCONNECTED71, UNCONNECTED72, UNCONNECTED73,
       UNCONNECTED74, UNCONNECTED75, UNCONNECTED76, UNCONNECTED77;
  wire UNCONNECTED78, UNCONNECTED79, UNCONNECTED80, UNCONNECTED81,
       UNCONNECTED82, UNCONNECTED83, UNCONNECTED84, UNCONNECTED85;
  wire UNCONNECTED86, UNCONNECTED87, UNCONNECTED88, UNCONNECTED89,
       UNCONNECTED90, UNCONNECTED91, UNCONNECTED92, UNCONNECTED93;
  wire UNCONNECTED94, UNCONNECTED95, UNCONNECTED96, UNCONNECTED97,
       UNCONNECTED98, UNCONNECTED99, UNCONNECTED100, UNCONNECTED101;
  wire UNCONNECTED102, UNCONNECTED103, UNCONNECTED104, UNCONNECTED105,
       UNCONNECTED106, UNCONNECTED107, UNCONNECTED108, UNCONNECTED109;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100;
  NAND2_X1 g2619__5122(.A1 (n_72), .A2 (n_99), .ZN (rd1[6]));
  NAND2_X1 g2620__8246(.A1 (n_62), .A2 (n_97), .ZN (rd1[3]));
  NAND2_X1 g2621__7098(.A1 (n_69), .A2 (n_100), .ZN (rd1[0]));
  NAND4_X1 g2622__6131(.A1 (n_46), .A2 (n_54), .A3 (n_45), .A4 (n_82),
       .ZN (rd1[2]));
  NAND2_X1 g2623__1881(.A1 (n_58), .A2 (n_98), .ZN (rd2[5]));
  NAND2_X1 g2624__5115(.A1 (n_78), .A2 (n_96), .ZN (rd2[1]));
  NAND4_X1 g2625__7482(.A1 (n_47), .A2 (n_67), .A3 (n_43), .A4 (n_85),
       .ZN (rd1[7]));
  NAND3_X1 g2626__4733(.A1 (n_65), .A2 (n_79), .A3 (n_91), .ZN
       (rd2[2]));
  AOI221_X1 g2627__6161(.A (n_94), .B1 (\RAM[6] [0]), .B2 (n_36), .C1
       (\RAM[5] [0]), .C2 (n_25), .ZN (n_100));
  AOI221_X1 g2628__9315(.A (n_88), .B1 (\RAM[6] [6]), .B2 (n_36), .C1
       (\RAM[5] [6]), .C2 (n_25), .ZN (n_99));
  AOI221_X1 g2629__9945(.A (n_87), .B1 (\RAM[5] [5]), .B2 (n_34), .C1
       (\RAM[6] [5]), .C2 (n_35), .ZN (n_98));
  AOI221_X1 g2630__2883(.A (n_89), .B1 (\RAM[6] [3]), .B2 (n_36), .C1
       (\RAM[5] [3]), .C2 (n_25), .ZN (n_97));
  NAND3_X1 g2631__2346(.A1 (n_77), .A2 (n_74), .A3 (n_93), .ZN
       (rd1[1]));
  AOI221_X1 g2632__1666(.A (n_95), .B1 (\RAM[5] [1]), .B2 (n_34), .C1
       (\RAM[6] [1]), .C2 (n_35), .ZN (n_96));
  NAND4_X1 g2633__7410(.A1 (n_40), .A2 (n_53), .A3 (n_52), .A4 (n_51),
       .ZN (rd2[3]));
  NAND4_X1 g2634__6417(.A1 (n_48), .A2 (n_70), .A3 (n_68), .A4 (n_81),
       .ZN (rd1[4]));
  NAND4_X1 g2635__5477(.A1 (n_41), .A2 (n_50), .A3 (n_64), .A4 (n_63),
       .ZN (rd2[7]));
  NAND4_X1 g2636__2398(.A1 (n_39), .A2 (n_61), .A3 (n_60), .A4 (n_59),
       .ZN (rd2[6]));
  NAND4_X1 g2637__5107(.A1 (n_49), .A2 (n_55), .A3 (n_66), .A4 (n_76),
       .ZN (rd1[5]));
  NAND4_X1 g2638__6260(.A1 (n_57), .A2 (n_44), .A3 (n_56), .A4 (n_80),
       .ZN (rd2[4]));
  NAND4_X1 g2639__4319(.A1 (n_75), .A2 (n_42), .A3 (n_73), .A4 (n_71),
       .ZN (rd2[0]));
  INV_X1 g2640(.A (n_92), .ZN (n_95));
  INV_X1 g2641(.A (n_90), .ZN (n_94));
  AOI222_X1 g2642__8428(.A1 (\RAM[1] [1]), .A2 (n_26), .B1 (\RAM[2]
       [1]), .B2 (n_38), .C1 (\RAM[5] [1]), .C2 (n_25), .ZN (n_93));
  AOI222_X1 g2643__5526(.A1 (\RAM[3] [1]), .A2 (n_30), .B1 (\RAM[4]
       [1]), .B2 (n_29), .C1 (\RAM[2] [1]), .C2 (n_28), .ZN (n_92));
  AOI222_X1 g2644__6783(.A1 (\RAM[1] [2]), .A2 (n_31), .B1 (\RAM[6]
       [2]), .B2 (n_35), .C1 (\RAM[7] [2]), .C2 (n_37), .ZN (n_91));
  AOI222_X1 g2645__3680(.A1 (\RAM[4] [0]), .A2 (n_33), .B1 (\RAM[3]
       [0]), .B2 (n_27), .C1 (\RAM[7] [0]), .C2 (n_32), .ZN (n_90));
  INV_X1 g2646(.A (n_86), .ZN (n_89));
  INV_X1 g2647(.A (n_84), .ZN (n_88));
  INV_X1 g2648(.A (n_83), .ZN (n_87));
  AOI222_X1 g2649__1617(.A1 (\RAM[4] [3]), .A2 (n_33), .B1 (\RAM[3]
       [3]), .B2 (n_27), .C1 (\RAM[7] [3]), .C2 (n_32), .ZN (n_86));
  AOI222_X1 g2650__2802(.A1 (\RAM[4] [7]), .A2 (n_33), .B1 (\RAM[3]
       [7]), .B2 (n_27), .C1 (\RAM[6] [7]), .C2 (n_36), .ZN (n_85));
  AOI222_X1 g2651__1705(.A1 (\RAM[4] [6]), .A2 (n_33), .B1 (\RAM[3]
       [6]), .B2 (n_27), .C1 (\RAM[7] [6]), .C2 (n_32), .ZN (n_84));
  AOI222_X1 g2652__5122(.A1 (\RAM[3] [5]), .A2 (n_30), .B1 (\RAM[4]
       [5]), .B2 (n_29), .C1 (\RAM[2] [5]), .C2 (n_28), .ZN (n_83));
  AOI222_X1 g2653__8246(.A1 (\RAM[4] [2]), .A2 (n_33), .B1 (\RAM[6]
       [2]), .B2 (n_36), .C1 (\RAM[7] [2]), .C2 (n_32), .ZN (n_82));
  AOI22_X1 g2654__7098(.A1 (\RAM[4] [4]), .A2 (n_33), .B1 (\RAM[3]
       [4]), .B2 (n_27), .ZN (n_81));
  AOI22_X1 g2655__6131(.A1 (\RAM[4] [4]), .A2 (n_29), .B1 (\RAM[2]
       [4]), .B2 (n_28), .ZN (n_80));
  AOI22_X1 g2656__1881(.A1 (\RAM[5] [2]), .A2 (n_34), .B1 (\RAM[3]
       [2]), .B2 (n_30), .ZN (n_79));
  AOI22_X1 g2657__5115(.A1 (\RAM[1] [1]), .A2 (n_31), .B1 (\RAM[7]
       [1]), .B2 (n_37), .ZN (n_78));
  AOI22_X1 g2658__7482(.A1 (\RAM[4] [1]), .A2 (n_33), .B1 (\RAM[3]
       [1]), .B2 (n_27), .ZN (n_77));
  AOI22_X1 g2659__4733(.A1 (\RAM[4] [5]), .A2 (n_33), .B1 (\RAM[3]
       [5]), .B2 (n_27), .ZN (n_76));
  AOI22_X1 g2660__6161(.A1 (\RAM[1] [0]), .A2 (n_31), .B1 (\RAM[7]
       [0]), .B2 (n_37), .ZN (n_75));
  AOI22_X1 g2661__9315(.A1 (\RAM[6] [1]), .A2 (n_36), .B1 (\RAM[7]
       [1]), .B2 (n_32), .ZN (n_74));
  AOI22_X1 g2662__9945(.A1 (\RAM[5] [0]), .A2 (n_34), .B1 (\RAM[3]
       [0]), .B2 (n_30), .ZN (n_73));
  AOI22_X1 g2663__2883(.A1 (\RAM[1] [6]), .A2 (n_26), .B1 (\RAM[2]
       [6]), .B2 (n_38), .ZN (n_72));
  AOI22_X1 g2664__2346(.A1 (\RAM[4] [0]), .A2 (n_29), .B1 (\RAM[2]
       [0]), .B2 (n_28), .ZN (n_71));
  AOI22_X1 g2665__1666(.A1 (\RAM[1] [4]), .A2 (n_26), .B1 (\RAM[2]
       [4]), .B2 (n_38), .ZN (n_70));
  AOI22_X1 g2666__7410(.A1 (\RAM[1] [0]), .A2 (n_26), .B1 (\RAM[2]
       [0]), .B2 (n_38), .ZN (n_69));
  AOI22_X1 g2667__6417(.A1 (\RAM[6] [4]), .A2 (n_36), .B1 (\RAM[7]
       [4]), .B2 (n_32), .ZN (n_68));
  AOI22_X1 g2668__5477(.A1 (\RAM[1] [7]), .A2 (n_26), .B1 (\RAM[2]
       [7]), .B2 (n_38), .ZN (n_67));
  AOI22_X1 g2669__2398(.A1 (\RAM[6] [5]), .A2 (n_36), .B1 (\RAM[7]
       [5]), .B2 (n_32), .ZN (n_66));
  AOI22_X1 g2670__5107(.A1 (\RAM[4] [2]), .A2 (n_29), .B1 (\RAM[2]
       [2]), .B2 (n_28), .ZN (n_65));
  AOI22_X1 g2671__6260(.A1 (\RAM[5] [7]), .A2 (n_34), .B1 (\RAM[3]
       [7]), .B2 (n_30), .ZN (n_64));
  AOI22_X1 g2672__4319(.A1 (\RAM[4] [7]), .A2 (n_29), .B1 (\RAM[2]
       [7]), .B2 (n_28), .ZN (n_63));
  AOI22_X1 g2673__8428(.A1 (\RAM[1] [3]), .A2 (n_26), .B1 (\RAM[2]
       [3]), .B2 (n_38), .ZN (n_62));
  AOI22_X1 g2674__5526(.A1 (\RAM[1] [6]), .A2 (n_31), .B1 (\RAM[7]
       [6]), .B2 (n_37), .ZN (n_61));
  AOI22_X1 g2675__6783(.A1 (\RAM[5] [6]), .A2 (n_34), .B1 (\RAM[3]
       [6]), .B2 (n_30), .ZN (n_60));
  AOI22_X1 g2676__3680(.A1 (\RAM[4] [6]), .A2 (n_29), .B1 (\RAM[2]
       [6]), .B2 (n_28), .ZN (n_59));
  AOI22_X1 g2677__1617(.A1 (\RAM[1] [5]), .A2 (n_31), .B1 (\RAM[7]
       [5]), .B2 (n_37), .ZN (n_58));
  AOI22_X1 g2678__2802(.A1 (\RAM[1] [4]), .A2 (n_31), .B1 (\RAM[7]
       [4]), .B2 (n_37), .ZN (n_57));
  AOI22_X1 g2679__1705(.A1 (\RAM[5] [4]), .A2 (n_34), .B1 (\RAM[3]
       [4]), .B2 (n_30), .ZN (n_56));
  AOI22_X1 g2680__5122(.A1 (\RAM[1] [5]), .A2 (n_26), .B1 (\RAM[2]
       [5]), .B2 (n_38), .ZN (n_55));
  AOI22_X1 g2681__8246(.A1 (\RAM[1] [2]), .A2 (n_26), .B1 (\RAM[2]
       [2]), .B2 (n_38), .ZN (n_54));
  AOI22_X1 g2682__7098(.A1 (\RAM[1] [3]), .A2 (n_31), .B1 (\RAM[7]
       [3]), .B2 (n_37), .ZN (n_53));
  AOI22_X1 g2683__6131(.A1 (\RAM[5] [3]), .A2 (n_34), .B1 (\RAM[3]
       [3]), .B2 (n_30), .ZN (n_52));
  AOI22_X1 g2684__1881(.A1 (\RAM[4] [3]), .A2 (n_29), .B1 (\RAM[2]
       [3]), .B2 (n_28), .ZN (n_51));
  AOI22_X1 g2685__5115(.A1 (\RAM[1] [7]), .A2 (n_31), .B1 (\RAM[7]
       [7]), .B2 (n_37), .ZN (n_50));
  NAND2_X1 g2686__7482(.A1 (\RAM[5] [5]), .A2 (n_25), .ZN (n_49));
  NAND2_X1 g2687__4733(.A1 (\RAM[5] [4]), .A2 (n_25), .ZN (n_48));
  NAND2_X1 g2688__6161(.A1 (\RAM[5] [7]), .A2 (n_25), .ZN (n_47));
  NAND2_X1 g2689__9315(.A1 (\RAM[5] [2]), .A2 (n_25), .ZN (n_46));
  NAND2_X1 g2690__9945(.A1 (\RAM[3] [2]), .A2 (n_27), .ZN (n_45));
  NAND2_X1 g2691__2883(.A1 (\RAM[6] [4]), .A2 (n_35), .ZN (n_44));
  NAND2_X1 g2692__2346(.A1 (\RAM[7] [7]), .A2 (n_32), .ZN (n_43));
  NAND2_X1 g2693__1666(.A1 (\RAM[6] [0]), .A2 (n_35), .ZN (n_42));
  NAND2_X1 g2694__7410(.A1 (\RAM[6] [7]), .A2 (n_35), .ZN (n_41));
  NAND2_X1 g2695__6417(.A1 (\RAM[6] [3]), .A2 (n_35), .ZN (n_40));
  NAND2_X1 g2696__5477(.A1 (\RAM[6] [6]), .A2 (n_35), .ZN (n_39));
  NOR2_X1 g2697__2398(.A1 (ra1[0]), .A2 (n_23), .ZN (n_38));
  NOR2_X1 g2698__5107(.A1 (n_15), .A2 (n_20), .ZN (n_37));
  NOR2_X1 g2699__6260(.A1 (ra1[0]), .A2 (n_19), .ZN (n_36));
  NOR2_X1 g2700__4319(.A1 (ra2[0]), .A2 (n_20), .ZN (n_35));
  NOR2_X1 g2701__8428(.A1 (n_15), .A2 (n_22), .ZN (n_34));
  NOR2_X1 g2702__5526(.A1 (ra1[0]), .A2 (n_21), .ZN (n_33));
  NOR2_X1 g2703__6783(.A1 (n_16), .A2 (n_19), .ZN (n_32));
  NOR3_X2 g2704__3680(.A1 (n_15), .A2 (ra2[2]), .A3 (ra2[1]), .ZN
       (n_31));
  NOR2_X1 g2705__1617(.A1 (n_15), .A2 (n_24), .ZN (n_30));
  NOR2_X1 g2706__2802(.A1 (ra2[0]), .A2 (n_22), .ZN (n_29));
  NOR2_X1 g2707__1705(.A1 (ra2[0]), .A2 (n_24), .ZN (n_28));
  NOR2_X1 g2708__5122(.A1 (n_16), .A2 (n_23), .ZN (n_27));
  NOR3_X2 g2709__8246(.A1 (n_16), .A2 (ra1[2]), .A3 (ra1[1]), .ZN
       (n_26));
  NOR2_X1 g2710__7098(.A1 (n_16), .A2 (n_21), .ZN (n_25));
  NAND2_X1 g2711__6131(.A1 (ra2[1]), .A2 (n_18), .ZN (n_24));
  NAND2_X1 g2712__1881(.A1 (ra1[1]), .A2 (n_14), .ZN (n_23));
  NAND2_X1 g2713__5115(.A1 (ra2[2]), .A2 (n_17), .ZN (n_22));
  OR2_X1 g2714__7482(.A1 (n_14), .A2 (ra1[1]), .ZN (n_21));
  NAND2_X1 g2715__4733(.A1 (ra2[2]), .A2 (ra2[1]), .ZN (n_20));
  NAND2_X1 g2716__6161(.A1 (ra1[2]), .A2 (ra1[1]), .ZN (n_19));
  INV_X1 g2717(.A (ra2[2]), .ZN (n_18));
  INV_X1 g2718(.A (ra2[1]), .ZN (n_17));
  INV_X1 g2719(.A (ra1[0]), .ZN (n_16));
  INV_X1 g2720(.A (ra2[0]), .ZN (n_15));
  INV_X1 g2721(.A (ra1[2]), .ZN (n_14));
  SDFF_X1 \RAM_reg[2][5] (.CK (clk), .D (\RAM[2] [5]), .SE (n_13), .SI
       (wd[5]), .Q (\RAM[2] [5]), .QN (UNCONNECTED54));
  SDFF_X1 \RAM_reg[2][4] (.CK (clk), .D (\RAM[2] [4]), .SE (n_13), .SI
       (wd[4]), .Q (\RAM[2] [4]), .QN (UNCONNECTED55));
  SDFF_X1 \RAM_reg[2][0] (.CK (clk), .D (\RAM[2] [0]), .SE (n_13), .SI
       (wd[0]), .Q (\RAM[2] [0]), .QN (UNCONNECTED56));
  SDFF_X1 \RAM_reg[2][6] (.CK (clk), .D (\RAM[2] [6]), .SE (n_13), .SI
       (wd[6]), .Q (\RAM[2] [6]), .QN (UNCONNECTED57));
  SDFF_X1 \RAM_reg[2][2] (.CK (clk), .D (\RAM[2] [2]), .SE (n_13), .SI
       (wd[2]), .Q (\RAM[2] [2]), .QN (UNCONNECTED58));
  SDFF_X1 \RAM_reg[2][1] (.CK (clk), .D (\RAM[2] [1]), .SE (n_13), .SI
       (wd[1]), .Q (\RAM[2] [1]), .QN (UNCONNECTED59));
  SDFF_X1 \RAM_reg[2][7] (.CK (clk), .D (\RAM[2] [7]), .SE (n_13), .SI
       (wd[7]), .Q (\RAM[2] [7]), .QN (UNCONNECTED60));
  SDFF_X1 \RAM_reg[2][3] (.CK (clk), .D (\RAM[2] [3]), .SE (n_13), .SI
       (wd[3]), .Q (\RAM[2] [3]), .QN (UNCONNECTED61));
  SDFF_X1 \RAM_reg[6][3] (.CK (clk), .D (\RAM[6] [3]), .SE (n_11), .SI
       (wd[3]), .Q (\RAM[6] [3]), .QN (UNCONNECTED62));
  SDFF_X1 \RAM_reg[6][4] (.CK (clk), .D (\RAM[6] [4]), .SE (n_11), .SI
       (wd[4]), .Q (\RAM[6] [4]), .QN (UNCONNECTED63));
  SDFF_X1 \RAM_reg[6][5] (.CK (clk), .D (\RAM[6] [5]), .SE (n_11), .SI
       (wd[5]), .Q (\RAM[6] [5]), .QN (UNCONNECTED64));
  SDFF_X1 \RAM_reg[6][6] (.CK (clk), .D (\RAM[6] [6]), .SE (n_11), .SI
       (wd[6]), .Q (\RAM[6] [6]), .QN (UNCONNECTED65));
  SDFF_X1 \RAM_reg[6][7] (.CK (clk), .D (\RAM[6] [7]), .SE (n_11), .SI
       (wd[7]), .Q (\RAM[6] [7]), .QN (UNCONNECTED66));
  SDFF_X1 \RAM_reg[7][0] (.CK (clk), .D (\RAM[7] [0]), .SE (n_9), .SI
       (wd[0]), .Q (\RAM[7] [0]), .QN (UNCONNECTED67));
  SDFF_X1 \RAM_reg[1][1] (.CK (clk), .D (wd[1]), .SE (n_7), .SI
       (\RAM[1] [1]), .Q (\RAM[1] [1]), .QN (UNCONNECTED68));
  SDFF_X1 \RAM_reg[7][1] (.CK (clk), .D (\RAM[7] [1]), .SE (n_9), .SI
       (wd[1]), .Q (\RAM[7] [1]), .QN (UNCONNECTED69));
  SDFF_X1 \RAM_reg[7][2] (.CK (clk), .D (\RAM[7] [2]), .SE (n_9), .SI
       (wd[2]), .Q (\RAM[7] [2]), .QN (UNCONNECTED70));
  SDFF_X1 \RAM_reg[3][0] (.CK (clk), .D (\RAM[3] [0]), .SE (n_12), .SI
       (wd[0]), .Q (\RAM[3] [0]), .QN (UNCONNECTED71));
  SDFF_X1 \RAM_reg[3][1] (.CK (clk), .D (\RAM[3] [1]), .SE (n_12), .SI
       (wd[1]), .Q (\RAM[3] [1]), .QN (UNCONNECTED72));
  SDFF_X1 \RAM_reg[7][3] (.CK (clk), .D (\RAM[7] [3]), .SE (n_9), .SI
       (wd[3]), .Q (\RAM[7] [3]), .QN (UNCONNECTED73));
  SDFF_X1 \RAM_reg[7][4] (.CK (clk), .D (\RAM[7] [4]), .SE (n_9), .SI
       (wd[4]), .Q (\RAM[7] [4]), .QN (UNCONNECTED74));
  SDFF_X1 \RAM_reg[7][5] (.CK (clk), .D (\RAM[7] [5]), .SE (n_9), .SI
       (wd[5]), .Q (\RAM[7] [5]), .QN (UNCONNECTED75));
  SDFF_X1 \RAM_reg[7][6] (.CK (clk), .D (\RAM[7] [6]), .SE (n_9), .SI
       (wd[6]), .Q (\RAM[7] [6]), .QN (UNCONNECTED76));
  SDFF_X1 \RAM_reg[3][2] (.CK (clk), .D (\RAM[3] [2]), .SE (n_12), .SI
       (wd[2]), .Q (\RAM[3] [2]), .QN (UNCONNECTED77));
  SDFF_X1 \RAM_reg[7][7] (.CK (clk), .D (\RAM[7] [7]), .SE (n_9), .SI
       (wd[7]), .Q (\RAM[7] [7]), .QN (UNCONNECTED78));
  SDFF_X1 \RAM_reg[3][3] (.CK (clk), .D (\RAM[3] [3]), .SE (n_12), .SI
       (wd[3]), .Q (\RAM[3] [3]), .QN (UNCONNECTED79));
  SDFF_X1 \RAM_reg[1][2] (.CK (clk), .D (wd[2]), .SE (n_7), .SI
       (\RAM[1] [2]), .Q (\RAM[1] [2]), .QN (UNCONNECTED80));
  SDFF_X1 \RAM_reg[3][4] (.CK (clk), .D (\RAM[3] [4]), .SE (n_12), .SI
       (wd[4]), .Q (\RAM[3] [4]), .QN (UNCONNECTED81));
  SDFF_X1 \RAM_reg[3][5] (.CK (clk), .D (\RAM[3] [5]), .SE (n_12), .SI
       (wd[5]), .Q (\RAM[3] [5]), .QN (UNCONNECTED82));
  SDFF_X1 \RAM_reg[3][6] (.CK (clk), .D (\RAM[3] [6]), .SE (n_12), .SI
       (wd[6]), .Q (\RAM[3] [6]), .QN (UNCONNECTED83));
  SDFF_X1 \RAM_reg[3][7] (.CK (clk), .D (\RAM[3] [7]), .SE (n_12), .SI
       (wd[7]), .Q (\RAM[3] [7]), .QN (UNCONNECTED84));
  SDFF_X1 \RAM_reg[1][3] (.CK (clk), .D (wd[3]), .SE (n_7), .SI
       (\RAM[1] [3]), .Q (\RAM[1] [3]), .QN (UNCONNECTED85));
  SDFF_X1 \RAM_reg[4][0] (.CK (clk), .D (wd[0]), .SE (n_8), .SI
       (\RAM[4] [0]), .Q (\RAM[4] [0]), .QN (UNCONNECTED86));
  SDFF_X1 \RAM_reg[4][1] (.CK (clk), .D (wd[1]), .SE (n_8), .SI
       (\RAM[4] [1]), .Q (\RAM[4] [1]), .QN (UNCONNECTED87));
  SDFF_X1 \RAM_reg[1][4] (.CK (clk), .D (wd[4]), .SE (n_7), .SI
       (\RAM[1] [4]), .Q (\RAM[1] [4]), .QN (UNCONNECTED88));
  SDFF_X1 \RAM_reg[4][2] (.CK (clk), .D (wd[2]), .SE (n_8), .SI
       (\RAM[4] [2]), .Q (\RAM[4] [2]), .QN (UNCONNECTED89));
  SDFF_X1 \RAM_reg[4][3] (.CK (clk), .D (wd[3]), .SE (n_8), .SI
       (\RAM[4] [3]), .Q (\RAM[4] [3]), .QN (UNCONNECTED90));
  SDFF_X1 \RAM_reg[1][6] (.CK (clk), .D (wd[6]), .SE (n_7), .SI
       (\RAM[1] [6]), .Q (\RAM[1] [6]), .QN (UNCONNECTED91));
  SDFF_X1 \RAM_reg[4][4] (.CK (clk), .D (wd[4]), .SE (n_8), .SI
       (\RAM[4] [4]), .Q (\RAM[4] [4]), .QN (UNCONNECTED92));
  SDFF_X1 \RAM_reg[4][5] (.CK (clk), .D (wd[5]), .SE (n_8), .SI
       (\RAM[4] [5]), .Q (\RAM[4] [5]), .QN (UNCONNECTED93));
  SDFF_X1 \RAM_reg[4][6] (.CK (clk), .D (wd[6]), .SE (n_8), .SI
       (\RAM[4] [6]), .Q (\RAM[4] [6]), .QN (UNCONNECTED94));
  SDFF_X1 \RAM_reg[4][7] (.CK (clk), .D (wd[7]), .SE (n_8), .SI
       (\RAM[4] [7]), .Q (\RAM[4] [7]), .QN (UNCONNECTED95));
  SDFF_X1 \RAM_reg[1][7] (.CK (clk), .D (wd[7]), .SE (n_7), .SI
       (\RAM[1] [7]), .Q (\RAM[1] [7]), .QN (UNCONNECTED96));
  SDFF_X1 \RAM_reg[5][0] (.CK (clk), .D (\RAM[5] [0]), .SE (n_10), .SI
       (wd[0]), .Q (\RAM[5] [0]), .QN (UNCONNECTED97));
  SDFF_X1 \RAM_reg[5][1] (.CK (clk), .D (\RAM[5] [1]), .SE (n_10), .SI
       (wd[1]), .Q (\RAM[5] [1]), .QN (UNCONNECTED98));
  SDFF_X1 \RAM_reg[5][2] (.CK (clk), .D (\RAM[5] [2]), .SE (n_10), .SI
       (wd[2]), .Q (\RAM[5] [2]), .QN (UNCONNECTED99));
  SDFF_X1 \RAM_reg[1][5] (.CK (clk), .D (wd[5]), .SE (n_7), .SI
       (\RAM[1] [5]), .Q (\RAM[1] [5]), .QN (UNCONNECTED100));
  SDFF_X1 \RAM_reg[5][3] (.CK (clk), .D (\RAM[5] [3]), .SE (n_10), .SI
       (wd[3]), .Q (\RAM[5] [3]), .QN (UNCONNECTED101));
  SDFF_X1 \RAM_reg[5][4] (.CK (clk), .D (\RAM[5] [4]), .SE (n_10), .SI
       (wd[4]), .Q (\RAM[5] [4]), .QN (UNCONNECTED102));
  SDFF_X1 \RAM_reg[5][5] (.CK (clk), .D (\RAM[5] [5]), .SE (n_10), .SI
       (wd[5]), .Q (\RAM[5] [5]), .QN (UNCONNECTED103));
  SDFF_X1 \RAM_reg[5][6] (.CK (clk), .D (\RAM[5] [6]), .SE (n_10), .SI
       (wd[6]), .Q (\RAM[5] [6]), .QN (UNCONNECTED104));
  SDFF_X1 \RAM_reg[5][7] (.CK (clk), .D (\RAM[5] [7]), .SE (n_10), .SI
       (wd[7]), .Q (\RAM[5] [7]), .QN (UNCONNECTED105));
  SDFF_X1 \RAM_reg[6][0] (.CK (clk), .D (\RAM[6] [0]), .SE (n_11), .SI
       (wd[0]), .Q (\RAM[6] [0]), .QN (UNCONNECTED106));
  SDFF_X1 \RAM_reg[1][0] (.CK (clk), .D (wd[0]), .SE (n_7), .SI
       (\RAM[1] [0]), .Q (\RAM[1] [0]), .QN (UNCONNECTED107));
  SDFF_X1 \RAM_reg[6][1] (.CK (clk), .D (\RAM[6] [1]), .SE (n_11), .SI
       (wd[1]), .Q (\RAM[6] [1]), .QN (UNCONNECTED108));
  SDFF_X1 \RAM_reg[6][2] (.CK (clk), .D (\RAM[6] [2]), .SE (n_11), .SI
       (wd[2]), .Q (\RAM[6] [2]), .QN (UNCONNECTED109));
  NOR3_X2 g2116__9315(.A1 (wa[0]), .A2 (wa[2]), .A3 (n_2), .ZN (n_13));
  NOR2_X1 g2117__9945(.A1 (n_2), .A2 (n_6), .ZN (n_12));
  NOR2_X1 g2118__2883(.A1 (n_2), .A2 (n_4), .ZN (n_11));
  NOR2_X1 g2119__2346(.A1 (n_3), .A2 (n_5), .ZN (n_10));
  NOR2_X1 g2120__1666(.A1 (n_2), .A2 (n_3), .ZN (n_9));
  OR2_X1 g2121__7410(.A1 (n_5), .A2 (n_4), .ZN (n_8));
  OR2_X1 g2122__6417(.A1 (n_6), .A2 (n_5), .ZN (n_7));
  NAND2_X1 g2123__5477(.A1 (wa[0]), .A2 (n_0), .ZN (n_6));
  NAND2_X1 g2124__2398(.A1 (regwrite), .A2 (n_1), .ZN (n_5));
  OR2_X1 g2125__5107(.A1 (n_0), .A2 (wa[0]), .ZN (n_4));
  NAND2_X1 g2126__6260(.A1 (wa[2]), .A2 (wa[0]), .ZN (n_3));
  NAND2_X1 g2127__4319(.A1 (regwrite), .A2 (wa[1]), .ZN (n_2));
  INV_X1 g2128(.A (wa[1]), .ZN (n_1));
  INV_X1 g2129(.A (wa[2]), .ZN (n_0));
endmodule

module mux2_WIDTH8_36(d0, d1, s, y);
  input [7:0] d0, d1;
  input s;
  output [7:0] y;
  wire [7:0] d0, d1;
  wire s;
  wire [7:0] y;
  MUX2_X1 g148__8428(.A (d0[1]), .B (d1[1]), .S (s), .Z (y[1]));
  MUX2_X1 g149__5526(.A (d0[4]), .B (d1[4]), .S (s), .Z (y[4]));
  MUX2_X1 g150__6783(.A (d0[7]), .B (d1[7]), .S (s), .Z (y[7]));
  MUX2_X1 g151__3680(.A (d0[0]), .B (d1[0]), .S (s), .Z (y[0]));
  MUX2_X1 g152__1617(.A (d0[5]), .B (d1[5]), .S (s), .Z (y[5]));
  MUX2_X1 g153__2802(.A (d0[6]), .B (d1[6]), .S (s), .Z (y[6]));
  MUX2_X1 g154__1705(.A (d0[3]), .B (d1[3]), .S (s), .Z (y[3]));
  MUX2_X1 g155__5122(.A (d0[2]), .B (d1[2]), .S (s), .Z (y[2]));
endmodule

module flop_WIDTH8_52(clk, d, q);
  input clk;
  input [7:0] d;
  output [7:0] q;
  wire clk;
  wire [7:0] d;
  wire [7:0] q;
  wire UNCONNECTED110, UNCONNECTED111, UNCONNECTED112, UNCONNECTED113,
       UNCONNECTED114, UNCONNECTED115, UNCONNECTED116, UNCONNECTED117;
  DFF_X1 \q_reg[2] (.CK (clk), .D (d[2]), .Q (q[2]), .QN
       (UNCONNECTED110));
  DFF_X1 \q_reg[1] (.CK (clk), .D (d[1]), .Q (q[1]), .QN
       (UNCONNECTED111));
  DFF_X1 \q_reg[0] (.CK (clk), .D (d[0]), .Q (q[0]), .QN
       (UNCONNECTED112));
  DFF_X1 \q_reg[3] (.CK (clk), .D (d[3]), .Q (q[3]), .QN
       (UNCONNECTED113));
  DFF_X1 \q_reg[6] (.CK (clk), .D (d[6]), .Q (q[6]), .QN
       (UNCONNECTED114));
  DFF_X1 \q_reg[5] (.CK (clk), .D (d[5]), .Q (q[5]), .QN
       (UNCONNECTED115));
  DFF_X1 \q_reg[4] (.CK (clk), .D (d[4]), .Q (q[4]), .QN
       (UNCONNECTED116));
  DFF_X1 \q_reg[7] (.CK (clk), .D (d[7]), .Q (q[7]), .QN
       (UNCONNECTED117));
endmodule

module zerodetect_WIDTH8(a, y);
  input [7:0] a;
  output y;
  wire [7:0] a;
  wire y;
  wire n_0, n_1;
  NOR4_X1 g40__8246(.A1 (a[7]), .A2 (a[0]), .A3 (n_0), .A4 (n_1), .ZN
       (y));
  OR4_X1 g41__7098(.A1 (a[6]), .A2 (a[5]), .A3 (a[4]), .A4 (a[3]), .ZN
       (n_1));
  OR2_X1 g42__6131(.A1 (a[2]), .A2 (a[1]), .ZN (n_0));
endmodule

module datapath_WIDTH8_REGBITS3(clk, reset, memdata, alusrca, memtoreg,
     iord, pcen, regwrite, regdst, pcsource, alusrcb, irwrite, alucont,
     zero, instr, adr, writedata);
  input clk, reset, alusrca, memtoreg, iord, pcen, regwrite, regdst;
  input [7:0] memdata;
  input [1:0] pcsource, alusrcb;
  input [3:0] irwrite;
  input [2:0] alucont;
  output zero;
  output [31:0] instr;
  output [7:0] adr, writedata;
  wire clk, reset, alusrca, memtoreg, iord, pcen, regwrite, regdst;
  wire [7:0] memdata;
  wire [1:0] pcsource, alusrcb;
  wire [3:0] irwrite;
  wire [2:0] alucont;
  wire zero;
  wire [31:0] instr;
  wire [7:0] adr, writedata;
  wire [7:0] pc;
  wire [7:0] aluout;
  wire [7:0] rd1;
  wire [7:0] a;
  wire [2:0] ra1;
  wire [7:0] md;
  wire [2:0] wa;
  wire [7:0] wd;
  wire [7:0] rd2;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6;
  wire UNCONNECTED_HIER_Z7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_174, n_175;
  wire n_208, n_209, n_210, n_211, n_212, n_213;
  mux2_WIDTH8 adrmux(pc, aluout, iord, adr);
  flop_WIDTH8_53 areg(clk, rd1, a);
  flopen_WIDTH8 ir0(clk, irwrite[0], memdata, {n_174, n_175,
       instr[5:0]});
  flopen_WIDTH8_56 ir1(clk, irwrite[1], {UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, memdata[5:3], UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z}, {n_159, n_160, n_208,
       n_209, n_210, n_161, n_162, n_163});
  flopen_WIDTH8_55 ir2(clk, irwrite[2], {memdata[7:5],
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, memdata[2:0]}, {ra1,
       n_157, n_158, n_211, n_212, n_213});
  flopen_WIDTH8_54 ir3(clk, irwrite[3], {memdata[7:2],
       UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6}, {instr[31:26], n_155,
       n_156});
  flop_WIDTH8 mdr(clk, memdata, md);
  flopenr_WIDTH8 pcreg(clk, reset, pcen, {n_132, n_131, n_130, n_129,
       n_128, n_127, n_126, n_125}, pc);
  mux2_WIDTH3 regmux({n_211, n_212, n_213}, {n_208, n_209, n_210},
       regdst, wa);
  flop_WIDTH8_51 res(clk, {n_140, n_139, n_138, n_137, n_136, n_135,
       n_134, n_133}, aluout);
  regfile_WIDTH8_REGBITS3 rf(clk, regwrite, ra1, {n_211, n_212, n_213},
       wa, wd, rd1, rd2);
  mux2_WIDTH8_36 wdmux(aluout, md, memtoreg, wd);
  flop_WIDTH8_52 wrd(clk, rd2, writedata);
  zerodetect_WIDTH8 zd({n_140, n_139, n_138, n_137, n_136, n_135,
       n_134, n_133}, zero);
  INV_X1 g3114(.A (n_123), .ZN (n_132));
  AOI222_X1 g3115__1881(.A1 (n_9), .A2 (n_140), .B1 (instr[5]), .B2
       (n_19), .C1 (aluout[7]), .C2 (n_18), .ZN (n_123));
  INV_X1 g3116(.A (n_122), .ZN (n_125));
  AOI22_X1 g3117__5115(.A1 (n_9), .A2 (n_133), .B1 (aluout[0]), .B2
       (n_18), .ZN (n_122));
  INV_X1 g3118(.A (n_121), .ZN (n_131));
  AOI222_X1 g3119__7482(.A1 (n_9), .A2 (n_139), .B1 (instr[4]), .B2
       (n_19), .C1 (aluout[6]), .C2 (n_18), .ZN (n_121));
  OAI211_X1 g3120__4733(.A (n_119), .B (n_96), .C1 (n_36), .C2 (n_31),
       .ZN (n_133));
  INV_X1 g3121(.A (n_120), .ZN (n_130));
  AOI222_X1 g3122__6161(.A1 (n_9), .A2 (n_138), .B1 (instr[3]), .B2
       (n_19), .C1 (aluout[5]), .C2 (n_18), .ZN (n_120));
  OAI222_X1 g3123__9315(.A1 (n_16), .A2 (n_116), .B1 (n_48), .B2
       (n_41), .C1 (n_15), .C2 (n_29), .ZN (n_140));
  NAND3_X1 g3124__9945(.A1 (alucont[0]), .A2 (alucont[1]), .A3 (n_115),
       .ZN (n_119));
  OAI221_X1 g3125__2883(.A (n_114), .B1 (n_51), .B2 (n_40), .C1 (n_15),
       .C2 (n_27), .ZN (n_139));
  INV_X1 g3126(.A (n_118), .ZN (n_129));
  AOI222_X1 g3127__2346(.A1 (n_9), .A2 (n_137), .B1 (instr[2]), .B2
       (n_19), .C1 (aluout[4]), .C2 (n_18), .ZN (n_118));
  OAI221_X1 g3128__1666(.A (n_113), .B1 (n_55), .B2 (n_38), .C1 (n_15),
       .C2 (n_24), .ZN (n_138));
  INV_X1 g3129(.A (n_117), .ZN (n_128));
  AOI222_X1 g3130__7410(.A1 (n_9), .A2 (n_136), .B1 (instr[1]), .B2
       (n_19), .C1 (aluout[3]), .C2 (n_18), .ZN (n_117));
  INV_X1 g3131(.A (n_115), .ZN (n_116));
  XNOR2_X1 g3132__6417(.A (n_112), .B (n_83), .ZN (n_115));
  OAI221_X1 g3133__5477(.A (n_108), .B1 (n_56), .B2 (n_42), .C1 (n_15),
       .C2 (n_25), .ZN (n_137));
  OAI211_X1 g3134__2398(.A (n_17), .B (n_110), .C1 (n_89), .C2 (n_0),
       .ZN (n_114));
  OAI211_X1 g3135__5107(.A (n_109), .B (n_17), .C1 (n_88), .C2 (n_107),
       .ZN (n_113));
  AOI21_X1 g3136__6260(.A (n_76), .B1 (n_69), .B2 (n_0), .ZN (n_112));
  INV_X1 g3137(.A (n_111), .ZN (n_127));
  AOI222_X1 g3138__4319(.A1 (n_9), .A2 (n_135), .B1 (instr[0]), .B2
       (n_19), .C1 (aluout[2]), .C2 (n_18), .ZN (n_111));
  OAI221_X1 g3139__8428(.A (n_106), .B1 (n_46), .B2 (n_37), .C1 (n_15),
       .C2 (n_23), .ZN (n_136));
  NAND2_X1 g3140__5526(.A1 (n_89), .A2 (n_0), .ZN (n_110));
  NAND2_X1 g3141__6783(.A1 (n_88), .A2 (n_107), .ZN (n_109));
  OAI211_X1 g3142__3680(.A (n_105), .B (n_17), .C1 (n_85), .C2 (n_102),
       .ZN (n_108));
  OAI211_X1 g3145__1617(.A (n_103), .B (n_17), .C1 (n_86), .C2 (n_99),
       .ZN (n_106));
  AOI21_X1 g3146__2802(.A (n_71), .B1 (n_75), .B2 (n_101), .ZN (n_107));
  OAI221_X1 g3147__1705(.A (n_100), .B1 (n_15), .B2 (n_28), .C1 (n_52),
       .C2 (n_39), .ZN (n_135));
  NAND2_X1 g3148__5122(.A1 (n_85), .A2 (n_102), .ZN (n_105));
  INV_X1 g3149(.A (n_104), .ZN (n_126));
  AOI22_X1 g3150__8246(.A1 (n_9), .A2 (n_134), .B1 (aluout[1]), .B2
       (n_18), .ZN (n_104));
  NAND2_X1 g3151__7098(.A1 (n_86), .A2 (n_99), .ZN (n_103));
  INV_X1 g3152(.A (n_102), .ZN (n_101));
  OAI211_X1 g3153__6131(.A (n_98), .B (n_17), .C1 (n_90), .C2 (n_94),
       .ZN (n_100));
  AOI211_X1 g3154__1881(.A (n_78), .B (n_97), .C1 (n_73), .C2 (n_82),
       .ZN (n_102));
  AOI21_X1 g3155__5115(.A (n_73), .B1 (n_80), .B2 (n_93), .ZN (n_99));
  OAI222_X1 g3156__7482(.A1 (n_16), .A2 (n_91), .B1 (n_32), .B2 (n_54),
       .C1 (n_15), .C2 (n_22), .ZN (n_134));
  NAND2_X1 g3157__4733(.A1 (n_90), .A2 (n_94), .ZN (n_98));
  AND4_X1 g3158__6161(.A1 (n_65), .A2 (n_82), .A3 (n_80), .A4 (n_87),
       .ZN (n_97));
  AOI21_X1 g3159__9315(.A (n_92), .B1 (n_14), .B2 (n_20), .ZN (n_96));
  INV_X1 g3160(.A (n_94), .ZN (n_93));
  OAI21_X1 g3161__9945(.A (n_81), .B1 (n_68), .B2 (n_71), .ZN (n_95));
  AOI21_X1 g3162__2883(.A (n_63), .B1 (n_65), .B2 (n_70), .ZN (n_94));
  AOI211_X1 g3163__2346(.A (n_79), .B (n_16), .C1 (n_45), .C2 (n_58),
       .ZN (n_92));
  XOR2_X1 g3164__1666(.A (n_70), .B (n_77), .Z (n_91));
  OR2_X1 g3165__7410(.A1 (n_63), .A2 (n_70), .ZN (n_87));
  NAND2_X1 g3166__6417(.A1 (n_74), .A2 (n_80), .ZN (n_90));
  AOI21_X1 g3167__5477(.A (n_76), .B1 (n_27), .B2 (n_62), .ZN (n_89));
  OAI21_X1 g3168__2398(.A (n_81), .B1 (n_24), .B2 (n_66), .ZN (n_88));
  OAI21_X1 g3169__5107(.A (n_82), .B1 (n_23), .B2 (n_67), .ZN (n_86));
  NAND2_X1 g3170__6260(.A1 (n_72), .A2 (n_75), .ZN (n_85));
  NAND2_X1 g3171__4319(.A1 (n_81), .A2 (n_75), .ZN (n_84));
  XNOR2_X1 g3172__8428(.A (n_59), .B (n_29), .ZN (n_83));
  NOR2_X1 g3173__5526(.A1 (n_45), .A2 (n_58), .ZN (n_79));
  NOR2_X1 g3174__6783(.A1 (n_23), .A2 (n_67), .ZN (n_78));
  NAND2_X1 g3175__3680(.A1 (n_64), .A2 (n_65), .ZN (n_77));
  NAND2_X1 g3176__1617(.A1 (n_23), .A2 (n_67), .ZN (n_82));
  NAND2_X1 g3177__2802(.A1 (n_24), .A2 (n_66), .ZN (n_81));
  NAND2_X1 g3178__1705(.A1 (n_28), .A2 (n_60), .ZN (n_80));
  INV_X1 g3179(.A (n_73), .ZN (n_74));
  INV_X1 g3180(.A (n_71), .ZN (n_72));
  NAND2_X1 g3181__5122(.A1 (n_27), .A2 (n_62), .ZN (n_69));
  NOR2_X1 g3182__8246(.A1 (n_27), .A2 (n_62), .ZN (n_76));
  NOR2_X1 g3183__7098(.A1 (n_24), .A2 (n_66), .ZN (n_68));
  NAND2_X1 g3184__6131(.A1 (n_25), .A2 (n_61), .ZN (n_75));
  NOR2_X1 g3185__1881(.A1 (n_28), .A2 (n_60), .ZN (n_73));
  NOR2_X1 g3186__5115(.A1 (n_25), .A2 (n_61), .ZN (n_71));
  OAI21_X1 g3187__7482(.A (n_43), .B1 (n_21), .B2 (n_31), .ZN (n_70));
  INV_X1 g3188(.A (n_63), .ZN (n_64));
  XOR2_X1 g3189__4733(.A (n_37), .B (alucont[2]), .Z (n_67));
  XOR2_X1 g3190__6161(.A (n_38), .B (alucont[2]), .Z (n_66));
  NAND2_X1 g3191__9315(.A1 (n_22), .A2 (n_57), .ZN (n_65));
  NOR2_X1 g3192__9945(.A1 (n_22), .A2 (n_57), .ZN (n_63));
  XOR2_X1 g3193__2883(.A (n_40), .B (alucont[2]), .Z (n_62));
  XOR2_X1 g3194__2346(.A (n_42), .B (alucont[2]), .Z (n_61));
  XNOR2_X1 g3195__1666(.A (n_41), .B (alucont[2]), .ZN (n_59));
  XOR2_X1 g3196__7410(.A (n_39), .B (alucont[2]), .Z (n_60));
  NOR2_X1 g3197__6417(.A1 (n_44), .A2 (n_49), .ZN (n_58));
  XOR2_X1 g3198__5477(.A (alucont[2]), .B (n_32), .Z (n_57));
  INV_X1 g3199(.A (n_53), .ZN (n_56));
  INV_X1 g3200(.A (n_50), .ZN (n_55));
  INV_X1 g3201(.A (n_47), .ZN (n_54));
  OAI21_X1 g3202__2398(.A (n_15), .B1 (alucont[1]), .B2 (n_25), .ZN
       (n_53));
  NOR2_X1 g3203__5107(.A1 (n_14), .A2 (n_35), .ZN (n_52));
  NOR2_X1 g3204__6260(.A1 (n_14), .A2 (n_34), .ZN (n_51));
  OAI21_X1 g3205__4319(.A (n_15), .B1 (alucont[1]), .B2 (n_24), .ZN
       (n_50));
  NOR2_X1 g3206__8428(.A1 (alucont[2]), .A2 (n_31), .ZN (n_49));
  NOR2_X1 g3207__5526(.A1 (n_14), .A2 (n_33), .ZN (n_48));
  OAI21_X1 g3208__6783(.A (n_15), .B1 (alucont[1]), .B2 (n_22), .ZN
       (n_47));
  NOR2_X1 g3209__3680(.A1 (n_14), .A2 (n_30), .ZN (n_46));
  INV_X1 g3210(.A (n_43), .ZN (n_44));
  AOI21_X1 g3211__1617(.A (n_14), .B1 (n_7), .B2 (n_20), .ZN (n_36));
  AOI22_X1 g3212__2802(.A1 (alucont[2]), .A2 (n_21), .B1 (n_5), .B2
       (n_20), .ZN (n_45));
  NAND2_X1 g3213__1705(.A1 (alucont[2]), .A2 (n_31), .ZN (n_43));
  AOI222_X1 g3214__5122(.A1 (writedata[4]), .A2 (n_1), .B1 (instr[2]),
       .B2 (n_11), .C1 (instr[4]), .C2 (n_13), .ZN (n_42));
  AOI222_X1 g3215__8246(.A1 (writedata[7]), .A2 (n_1), .B1 (instr[5]),
       .B2 (n_11), .C1 (n_174), .C2 (n_13), .ZN (n_41));
  AOI222_X1 g3216__7098(.A1 (n_175), .A2 (n_13), .B1 (instr[4]), .B2
       (n_11), .C1 (writedata[6]), .C2 (n_1), .ZN (n_40));
  AOI221_X1 g3217__6131(.A (n_26), .B1 (writedata[2]), .B2 (n_1), .C1
       (instr[2]), .C2 (n_13), .ZN (n_39));
  AOI222_X1 g3218__1881(.A1 (instr[5]), .A2 (n_13), .B1 (instr[3]), .B2
       (n_11), .C1 (writedata[5]), .C2 (n_1), .ZN (n_38));
  AOI222_X1 g3219__5115(.A1 (instr[1]), .A2 (n_11), .B1 (writedata[3]),
       .B2 (n_1), .C1 (instr[3]), .C2 (n_13), .ZN (n_37));
  NOR2_X1 g3220__7482(.A1 (alucont[1]), .A2 (n_28), .ZN (n_35));
  NOR2_X1 g3221__4733(.A1 (alucont[1]), .A2 (n_27), .ZN (n_34));
  NOR2_X1 g3222__6161(.A1 (alucont[1]), .A2 (n_29), .ZN (n_33));
  NOR2_X1 g3223__9315(.A1 (alucont[1]), .A2 (n_23), .ZN (n_30));
  OAI221_X1 g3224__9945(.A (n_3), .B1 (n_2), .B2 (instr[1]), .C1
       (alusrcb[1]), .C2 (writedata[1]), .ZN (n_32));
  OAI221_X1 g3225__2883(.A (n_10), .B1 (writedata[0]), .B2 (n_12), .C1
       (n_2), .C2 (instr[0]), .ZN (n_31));
  AND3_X1 g3226__2346(.A1 (alusrcb[0]), .A2 (alusrcb[1]), .A3
       (instr[0]), .ZN (n_26));
  AOI22_X1 g3227__1666(.A1 (pc[7]), .A2 (n_6), .B1 (alusrca), .B2
       (a[7]), .ZN (n_29));
  AOI22_X1 g3228__7410(.A1 (pc[2]), .A2 (n_6), .B1 (alusrca), .B2
       (a[2]), .ZN (n_28));
  AOI22_X1 g3229__6417(.A1 (pc[6]), .A2 (n_6), .B1 (alusrca), .B2
       (a[6]), .ZN (n_27));
  INV_X1 g3230(.A (n_21), .ZN (n_20));
  AOI22_X1 g3231__5477(.A1 (pc[4]), .A2 (n_6), .B1 (alusrca), .B2
       (a[4]), .ZN (n_25));
  AOI22_X1 g3232__2398(.A1 (pc[5]), .A2 (n_6), .B1 (alusrca), .B2
       (a[5]), .ZN (n_24));
  AOI22_X1 g3233__5107(.A1 (pc[3]), .A2 (n_6), .B1 (alusrca), .B2
       (a[3]), .ZN (n_23));
  AOI22_X1 g3234__6260(.A1 (pc[1]), .A2 (n_6), .B1 (alusrca), .B2
       (a[1]), .ZN (n_22));
  AOI22_X1 g3235__4319(.A1 (pc[0]), .A2 (n_6), .B1 (alusrca), .B2
       (a[0]), .ZN (n_21));
  INV_X1 g3236(.A (n_17), .ZN (n_16));
  INV_X1 g3237(.A (n_15), .ZN (n_14));
  NOR2_X1 g3238__8428(.A1 (n_8), .A2 (pcsource[0]), .ZN (n_19));
  NOR2_X1 g3239__5526(.A1 (n_4), .A2 (pcsource[1]), .ZN (n_18));
  NOR2_X1 g3240__6783(.A1 (n_7), .A2 (alucont[0]), .ZN (n_17));
  NAND2_X1 g3241__3680(.A1 (alucont[0]), .A2 (n_7), .ZN (n_15));
  INV_X1 g3242(.A (n_1), .ZN (n_12));
  INV_X1 g3243(.A (n_11), .ZN (n_10));
  NOR2_X1 g3245__1617(.A1 (n_2), .A2 (alusrcb[0]), .ZN (n_13));
  NOR2_X1 g3247__2802(.A1 (n_2), .A2 (n_3), .ZN (n_11));
  NOR2_X1 g3248__1705(.A1 (pcsource[1]), .A2 (pcsource[0]), .ZN (n_9));
  INV_X1 g3249(.A (pcsource[1]), .ZN (n_8));
  INV_X1 g3250(.A (alucont[1]), .ZN (n_7));
  INV_X1 g3251(.A (alusrca), .ZN (n_6));
  INV_X1 g3252(.A (alucont[2]), .ZN (n_5));
  INV_X1 g3253(.A (pcsource[0]), .ZN (n_4));
  INV_X1 g3254(.A (alusrcb[0]), .ZN (n_3));
  INV_X1 g3255(.A (alusrcb[1]), .ZN (n_2));
  NOR2_X1 g3256__5122(.A1 (alusrcb[1]), .A2 (alusrcb[0]), .ZN (n_1));
  OAI21_X1 g3257__8246(.A (n_95), .B1 (n_84), .B2 (n_102), .ZN (n_0));
endmodule

module mips(clk, reset, memdata, memread, memwrite, adr, writedata);
  input clk, reset;
  input [7:0] memdata;
  output memread, memwrite;
  output [7:0] adr, writedata;
  wire clk, reset;
  wire [7:0] memdata;
  wire memread, memwrite;
  wire [7:0] adr, writedata;
  wire [1:0] aluop;
  wire [1:0] pcsource;
  wire [31:0] instr;
  wire [2:0] alucont;
  wire [1:0] alusrcb;
  wire [3:0] irwrite;
  wire UNCONNECTED118, alusrca, iord, memtoreg, pcen, regdst, regwrite,
       zero;
  alucontrol ac({aluop[1], pcsource[0]}, instr[5:0], alucont);
  controller cont(clk, reset, instr[31:26], zero, memread, memwrite,
       alusrca, memtoreg, iord, pcen, regwrite, regdst, pcsource,
       alusrcb, {aluop[1], UNCONNECTED118}, irwrite);
  datapath_WIDTH8_REGBITS3 dp(clk, reset, memdata, alusrca, memtoreg,
       iord, pcen, regwrite, regdst, pcsource, alusrcb, irwrite,
       alucont, zero, instr, adr, writedata);
endmodule

